### ISSUE TITLE
Does not work out the box following instructions

### ISSUE THREAD

**Issue by jeremykenedy** [invokemedia/vue-radio-checkbox#1]
Hi, 

Thank you for the repository, however, after the initial package install and adding the required statement to my main.js file I am receiving the error:

`Uncaught TypeError: Cannot read property 'component' of undefined(…)`

The details of the error are with the initial call from the plugin:

`window.Vue.component('checkbox', {`

Any ideas?

Thank you in advance:)

**Comment by james2doyle** [comment]
Sounds like Vue isn't loaded or the plugin is being required before Vue is loaded.

Are you waiting for a `DOMContentLoaded` event or a `Vue.created`/`Vue.mounted`?

**Comment by jeremykenedy** [comment]
Vue.mounted.  I was able to get it going. Thank you for the quick response 👍

**Comment by goors** [comment]
I am getting the same thing. How did you resolve this?
